### ISSUE TITLE
Correct BIC

### ISSUE THREAD

**Issue by pulseit-dennis** [jschaedl/Iban#13]
Hi,

returning the correct BIC may also be important, and (for Germany) it depends on the the IBAN-Rules. For example, rule 0005xx states, that all Commerzbank AG-accounts (BLZ ***4xx**) have the BIC COBADEFFXXX, except for all comdirect-Accounts (000503).

What are your thoughts on that topic?

Cheers,

Dennis

**Comment by jschaedl** [comment]
No, you can't get the BIC with this class. But have a look at the [Bav lib](https://github.com/jschaedl/Bav). There you can get the BIC code with the help of the Agency class (see: https://github.com/jschaedl/Bav/blob/master/library/Bav/Bank/Agency.php)
